import { test, expect } from '@playwright/test';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

const root=path.resolve(process.cwd(),'..');
function password(){return execFileSync(path.join(root,'.venv/bin/python'),['-c','from edgemed.security import load_secret; print(load_secret("edge-a")["initial_password"])'],{cwd:root,encoding:'utf8'}).trim()}
test('desktop: sign in, search, inspect, create, graph and sync',async({page})=>{
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto('/');
  await expect(page.getByRole('heading',{name:'Unlock your workspace'})).toBeVisible();
  await page.getByLabel('Password',{exact:true}).fill(password());
  await page.getByRole('button',{name:'Sign in locally'}).click();
  await expect(page.getByRole('heading',{name:'Memory explorer',exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Load examples'}).click();
  await expect(page.getByText('Persistent cough and fever',{exact:true})).toBeVisible();
  await page.screenshot({path:path.join(root,'test-results/desktop.png'),fullPage:true});
  await page.getByRole('textbox',{name:'Search memory'}).fill('high temperature and coughing');
  await page.getByRole('button',{name:'Search',exact:true}).click();
  await expect(page.getByText(/ms · hybrid · local/)).toBeVisible();
  await page.getByText('Persistent cough and fever',{exact:true}).click();
  await expect(page.getByText('Kept on this device',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Close inspector'}).click();
  await page.getByRole('button',{name:'New observation'}).click();
  await page.getByLabel('Title',{exact:true}).fill('Browser verification observation');
  await page.getByLabel('Observation',{exact:true}).fill('<script>window.privateLeak=true</script> Synthetic observation.');
  await page.getByRole('button',{name:'Save locally'}).click();
  await expect(page.getByText('Browser verification observation',{exact:true})).toBeVisible();
  await page.getByText('Browser verification observation',{exact:true}).click();
  await expect(page.locator('.note-content')).toContainText('<script>');
  expect(await page.evaluate(()=>Object.hasOwn(window,'privateLeak'))).toBe(false);
  await page.getByText('Archive / deletion').click();
  await page.getByRole('button',{name:'Remove from active memory'}).click();
  await page.getByRole('button',{name:'Knowledge graph',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Connected memory'})).toBeVisible();
  await page.getByRole('button',{name:'Synchronization',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Transport paused'})).toBeVisible();
  await page.screenshot({path:path.join(root,'test-results/sync.png'),fullPage:true});
  await page.getByRole('button',{name:'Sign out'}).click();
  await expect(page.getByRole('heading',{name:'Unlock your workspace'})).toBeVisible();
  expect(errors).toEqual([]);
});
test('mobile: memory interface remains readable without horizontal overflow',async({page})=>{
  await page.setViewportSize({width:390,height:844});await page.goto('/');
  await page.getByLabel('Password',{exact:true}).fill(password());
  await page.getByRole('button',{name:'Sign in locally'}).click();
  await expect(page.getByRole('heading',{name:'Memory explorer',exact:true})).toBeVisible();
  await expect(page.getByText('Persistent cough and fever',{exact:true})).toBeVisible();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await page.screenshot({path:path.join(root,'test-results/mobile.png'),fullPage:true});
});
