import React, { useEffect, useState, type FormEvent } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowDownLeft, ArrowUpRight, Check, ChevronRight, Database, FileText, GitBranch, HardDrive, LockKeyhole, LogOut, Network, Plus, RefreshCw, Search, ShieldCheck, Wifi, WifiOff, X } from 'lucide-react';
import './style.css';

type Revision = {id:string;content:string;created:number;parents:string[];variant:number;device:string};
type Memory = {id:string;title:string;content:string;subject:string|null;category:string;privacy:string;release:string;reason:string;heads:string[];revisions:Revision[];fixture:string|null;conflicting:boolean;index_state:string;created:number;semantic_score?:number;keyword_score?:number};
type Status = {device:string;total:number;local_only:number;conflicts:number;indexed:number;engine:string;database:string;vault:boolean;worker_error:string|null};
type Sync = {enabled:boolean;error:string|null;last_sync?:number;items:{id:string;state:string;attempts:number;error:string|null;payload:unknown}[]};
let csrf = '';
async function api(path:string, method='GET', data?:unknown) {
  const res = await fetch('/api'+path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:data===undefined?undefined:JSON.stringify(data)});
  const body = await res.json();
  if(!res.ok) { if(res.status===401 && path!='/login') window.dispatchEvent(new Event('session-expired')); throw new Error(typeof body.detail==='string'?body.detail:'Please check the submitted fields.'); }
  return body;
}
const date = (t:number) => new Date(t*1000).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});

function App(){
  const [user,setUser]=useState(''),[checking,setChecking]=useState(true),[error,setError]=useState('');
  const [view,setView]=useState('Memory explorer'),[memories,setMemories]=useState<Memory[]>([]),[status,setStatus]=useState<Status|null>(null),[sync,setSync]=useState<Sync|null>(null);
  const [selected,setSelected]=useState<Memory|null>(null),[query,setQuery]=useState(''),[results,setResults]=useState<Memory[]|null>(null),[timing,setTiming]=useState<number|null>(null),[filter,setFilter]=useState('All memory'),[adding,setAdding]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const [events,setEvents]=useState<{action:string;time:number;device:string}[]>([]);
  async function refresh(){const [m,s,y,a]=await Promise.all([api('/memories'),api('/status'),api('/sync/status'),api('/activity')]);setMemories(m);setStatus(s);setSync(y);setEvents(a);setSelected(old=>old?m.find((r:Memory)=>r.id===old.id)||null:null);}
  useEffect(()=>{api('/session').then(s=>{csrf=s.csrf;setUser(s.username)}).catch(()=>{}).finally(()=>setChecking(false)); const expired=()=>{setUser('');setMemories([]);setResults(null);setSelected(null);setStatus(null);setSync(null);setEvents([]);csrf=''};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);
  useEffect(()=>{if(!user)return;refresh().catch(e=>setError(e.message));const t=setInterval(()=>refresh().catch(e=>setError(e.message)),3000);return()=>clearInterval(t)},[user]);
  async function action(fn:()=>Promise<unknown>, message=''){setBusy(true);setError('');try{await fn();await refresh();setResults(null);if(message)setNotice(message)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);setBusy(true);setError('');try{const s=await api('/login','POST',{username:d.get('username'),password:d.get('password')});csrf=s.csrf;setUser(s.username)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function search(e:FormEvent){e.preventDefault();if(!query.trim()){setResults(null);return}setBusy(true);try{const r=await api('/search','POST',{query,mode:'hybrid'});setResults(r.results);setTiming(r.elapsed_ms)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);await action(async()=>{await api('/memories','POST',{title:d.get('title'),content:d.get('content'),subject:d.get('subject'),category:d.get('category'),privacy:d.get('privacy')});setAdding(false)},'Observation saved locally. Search indexing follows automatically.');}
  const shown=(results??memories).filter(m=>filter==='All memory'||(filter==='Local only'&&!m.fixture)||(filter==='Shared references'&&m.fixture)||(filter==='Needs review'&&m.conflicting));
  if(checking)return <div className="loading">Opening local workspace…</div>;
  if(!user)return <div className="login-page"><div className="login-brand"><div className="brand-symbol"><GitBranch size={26}/></div><span>EdgeMed<span className="brand-dot">.</span></span></div><div className="login-copy"><div className="eyebrow">MEMORY THAT STAYS WITH YOU</div><h1>Intelligence here.<br/>Your data, here.</h1><p>An offline workspace for synthetic clinical memory.<br/>Search, inspect, and share only what is approved.</p><div className="login-features"><span><HardDrive size={17}/> Real Qdrant Edge</span><span><ShieldCheck size={17}/> Encrypted local vault</span></div></div><form className="login-card" onSubmit={login}><LockKeyhole size={25}/><h2>Unlock your workspace</h2><p>Your credentials are stored in macOS Keychain.</p><label>Username<input name="username" defaultValue="operator" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label>{error&&<div role="alert" className="error">{error}</div>}<button className="primary" disabled={busy}>{busy?'Signing in…':'Sign in locally'} <ArrowUpRight size={17}/></button><div className="help">Retrieve your generated password:<code>.venv/bin/python -m edgemed.cli credentials edge-a</code><small>Use edge-b for the second device.</small></div></form><footer>Synthetic data only · Local research prototype</footer></div>;
  return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brand-symbol"><GitBranch size={22}/></div>EdgeMed<span className="brand-dot">.</span></div><div className="workspace"><span className="device-avatar">LX</span><div><b>LEX workspace</b><small>Local memory lab</small></div><span className="tiny-dot"/></div><div className="nav-label">WORKSPACE</div><nav>{[[Database,'Memory explorer'],[Network,'Knowledge graph'],[RefreshCw,'Synchronization'],[Activity,'Activity & timeline']].map(([Icon,label])=>{const I=Icon as typeof Database;return <button key={label as string} className={view===label?'nav active':'nav'} onClick={()=>{setView(label as string);setSelected(null)}}><I size={18}/>{label as string}{label==='Memory explorer'&&<span className="nav-count">{status?.total??0}</span>}</button>})}</nav><div className="sidebar-bottom"><div className="protection"><ShieldCheck size={20}/><div><b>Local by default</b><p>Private observations stay<br/>on this device.</p></div></div><button className="nav" onClick={async()=>{try{await api('/logout','POST');setError('');setNotice('');window.dispatchEvent(new Event('session-expired'))}catch(e){setError((e as Error).message)}}}><LogOut size={17}/>Sign out</button><div className="version">LEX / PS03 <span>v0.1.0</span></div></div></aside>
    <main><header className="topbar"><span>Workspace <ChevronRight size={14}/> <b>{view}</b></span><div className="topbar-right"><span className="synthetic">SYNTHETIC DATA</span><span className="device-chip"><span className="tiny-dot"/>{status?.device??'edge'}</span></div></header><div className="page"><div className="page-heading"><div><div className="eyebrow">ON-DEVICE INTELLIGENCE</div><h1>{view}</h1><p>{view==='Memory explorer'?'A clear view of what your device remembers.':view==='Synchronization'?'Every shared operation, with a reason and a receipt.':view==='Knowledge graph'?'Explore the connections behind your observations.':'Follow the history of your local workspace.'}</p></div><button className="primary" onClick={()=>setAdding(true)}><Plus size={17}/>New observation</button></div>
    {error&&<div role="alert" className="error banner">{error}<button aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}{notice&&<div className="notice banner"><Check size={16}/>{notice}<button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    <div className="stats"><Stat label="TOTAL MEMORIES" value={status?.total??0} icon={<Database size={18}/>} note={`${status?.indexed??0} indexed for local search`}/><Stat label="KEPT ON DEVICE" value={status?.local_only??0} icon={<LockKeyhole size={18}/>} note="Private by policy"/><Stat label="SYNC QUEUE" value={sync?.items.filter(x=>!['acknowledged','cancelled'].includes(x.state)).length??0} icon={<RefreshCw size={18}/>} note={sync?.enabled?'Transport enabled':'Transport paused'}/><Stat label="NEEDS REVIEW" value={status?.conflicts??0} icon={<GitBranch size={18}/>} note="Conflicting observations"/></div>
    <div className="security-strip"><ShieldCheck size={19}/><span><b>{status?.vault?'Encrypted vault active':'Synthetic test workspace'}</b> · SQLCipher records + protected vector storage</span><span className="local-route"><HardDrive size={14}/> LOCAL SEARCH</span></div>
    {view==='Memory explorer'&&<><div className="toolbar"><form className="search" onSubmit={search}><Search size={18}/><input aria-label="Search memory" placeholder="Search by meaning, symptom, or exact term…" value={query} onChange={e=>setQuery(e.target.value)}/><button disabled={busy}>Search</button></form><button className="secondary" disabled={busy} onClick={()=>action(()=>api('/demo/seed','POST'),'Synthetic examples are ready to explore.')}><Plus size={16}/>Load examples</button></div><div className="tabs">{['All memory','Local only','Shared references','Needs review'].map(t=><button className={filter===t?'selected':''} key={t} onClick={()=>setFilter(t)}>{t}</button>)}<span>{results?`${timing} ms · hybrid · local`:`${shown.length} records`}</span>{results&&<button onClick={()=>{setResults(null);setQuery('')}}>Clear search</button>}</div><div className="memory-table"><div className="table-head"><span>MEMORY / SOURCE</span><span>PRIVACY</span><span>STATE</span><span>CAPTURED</span><span/></div>{shown.map(m=><button className="memory-row" key={m.id} onClick={()=>setSelected(m)}><span className="memory-name"><span className={'record-icon '+(m.fixture?'reference':'')}><FileText size={19}/></span><span><b>{m.title}</b><small>{m.subject??'Reviewed reference'} <i>·</i> {m.category.toLowerCase().replace('_',' ')}</small></span></span><span><span className={'badge '+(m.fixture?'teal':'neutral')}>{m.fixture?<ArrowUpRight size={12}/>:<LockKeyhole size={11}/>} {m.fixture?'Approved reference':'Local only'}</span></span><span className={m.conflicting?'conflict':'state'}><span className="tiny-dot"/>{m.conflicting?'Needs review':m.index_state==='indexed'?'Searchable':'Indexing'}</span><span className="date">{date(m.created)}</span><ChevronRight size={15}/></button>)}{shown.length===0&&<div className="empty"><Database size={34}/><h3>{results?'No matching memories':'A fresh start for local memory'}</h3><p>{results?'Try a broader phrase or load synthetic examples.':'Add an observation or load the synthetic examples to begin.'}</p></div>}</div><div className="table-footer"><span><LockKeyhole size={13}/> Patient observations are never added to the outbound queue.</span><span>Qdrant Edge · {status?.database}</span></div></>}
    {view==='Synchronization'&&<section className="panel"><div className="panel-heading"><div><h2>{sync?.enabled?'Transport enabled':'Transport paused'}</h2><p>Only approved synthetic reference versions can be shared.</p></div><button className="secondary" disabled={busy} onClick={()=>action(()=>api('/sync/transport','POST',{enabled:!sync?.enabled}))}>{sync?.enabled?<WifiOff size={16}/>:<Wifi size={16}/>} {sync?.enabled?'Pause transport':'Enable transport'}</button><button className="primary" disabled={busy||!sync?.enabled} onClick={()=>action(()=>api('/sync','POST'))}><RefreshCw size={16}/>Sync now</button><button className="secondary" disabled={busy||!sync?.enabled} onClick={()=>action(()=>api('/sync/reference-snapshot','POST'),'Signed reference cache verified and loaded.')}>Refresh reference cache</button></div>{sync?.error&&<p className="error">{sync.error}</p>}{sync?.items.length?sync.items.map(item=><details className="sync-item" key={item.id}><summary><span><ArrowUpRight size={16}/> Approved reference operation</span><span className={'badge '+(item.state==='acknowledged'?'teal':'neutral')}>{item.state}</span></summary><p>{item.attempts} attempts · {item.error??'Private note content and embeddings are excluded.'}</p><pre>{JSON.stringify(item.payload,null,2)}</pre></details>):<div className="empty"><RefreshCw size={30}/><h3>Nothing waiting to leave</h3><p>Load synthetic reference examples to demonstrate selective sync.</p></div>}</section>}
    {view==='Knowledge graph'&&<section className="panel"><div className="panel-heading"><div><h2>Connected memory</h2><p>Explicit subject links, supported by your saved observations.</p></div><span className="badge neutral">Scoped to this operator</span></div><div className="graph-grid">{Array.from(new Set(memories.map(m=>m.subject??'Shared references'))).map(subject=><div className="graph-group" key={subject}><div className="subject-node"><Network size={20}/>{subject}</div><div className="graph-children">{memories.filter(m=>(m.subject??'Shared references')===subject).map(m=><button onClick={()=>setSelected(m)} key={m.id}><span className="line"/><FileText size={15}/><span>{m.title}<small>{m.category.toLowerCase()}</small></span></button>)}</div></div>)}</div>{!memories.length&&<div className="empty">Load examples to explore their relationships.</div>}</section>}
    {view==='Activity & timeline'&&<section className="panel"><div className="panel-heading"><div><h2>Local activity</h2><p>Authenticated event chain. Sensitive note text is excluded.</p></div><span className="badge teal"><ShieldCheck size={13}/>HMAC verified at startup</span></div><div className="timeline">{events.map((e,i)=><div key={i}><span className="timeline-dot"/><b>{e.action.replaceAll('_',' ')}</b><span>{e.device}</span><time>{date(e.time)}</time></div>)}</div></section>}
    <footer className="page-footer"><span>Built for disconnected moments.</span><span>Research prototype · Synthetic data only</span></footer></div></main>
    {selected&&<div className="overlay" onClick={()=>setSelected(null)}><aside className="inspector" onClick={e=>e.stopPropagation()}><div className="inspector-top"><span className="eyebrow">MEMORY INSPECTOR</span><button aria-label="Close inspector" onClick={()=>setSelected(null)}><X/></button></div><span className={'badge '+(selected.fixture?'teal':'neutral')}>{selected.privacy}</span><h2>{selected.title}</h2><p className="muted">{selected.subject??'Reviewed synthetic reference'} · {selected.category}</p><div className="note-content">{selected.content}</div><div className="policy-box"><ShieldCheck size={19}/><div><b>{selected.fixture?'Eligible for selective sharing':'Kept on this device'}</b><p>{selected.reason}</p></div></div><h3>Revision history</h3>{selected.revisions.map(r=><div className="revision" key={r.id}><div><GitBranch size={14}/><b>{selected.heads.includes(r.id)?'Current branch':'Previous revision'}</b><small>{date(r.created)}</small></div><p>{r.content}</p><small>{r.device} · {r.id.slice(0,8)}</small>{selected.conflicting&&selected.heads.includes(r.id)&&<button className="secondary" disabled={busy} onClick={()=>action(()=>api(`/memories/${selected.id}/resolve`,'POST',{parents:selected.heads,chosen:r.id}),'Conflict resolved with a new revision.')}>Resolve using this branch</button>}</div>)}{selected.fixture?<div className="variant-controls"><h3>Reference revision demo</h3><p className="muted">Select a reviewed variant. Concurrent device edits are preserved for review.</p>{[1,2].map(v=><button className="secondary" key={v} disabled={busy} onClick={()=>action(()=>api(`/memories/${selected.id}/reference-variant`,'POST',{parent:selected.heads[0],variant:v}),`Reference variant ${v} saved.`)}>Save variant {v}</button>)}</div>:<form onSubmit={e=>{e.preventDefault();const d=new FormData(e.currentTarget);action(()=>api(`/memories/${selected.id}/revisions`,'POST',{parent:selected.heads[0],content:d.get('content')}),'New local revision saved.')}}><label>Add a corrected observation<textarea name="content" required maxLength={12000} placeholder="The original remains in revision history."/></label><button className="secondary" disabled={busy}>Save revision</button></form>}<details className="danger-zone"><summary>Archive / deletion</summary><p>Remove this memory from search and queue a tombstone for a shared reference. Protected history remains in the local audit store.</p><button className="danger" disabled={busy} onClick={()=>action(async()=>{await api(`/memories/${selected.id}`,'DELETE');setSelected(null)},'Memory removed from active search.')}>Remove from active memory</button></details></aside></div>}
    {adding&&<div className="overlay" onClick={()=>setAdding(false)}><form className="modal" onClick={e=>e.stopPropagation()} onSubmit={create}><div className="inspector-top"><span className="eyebrow">NEW LOCAL MEMORY</span><button type="button" aria-label="Close form" onClick={()=>setAdding(false)}><X/></button></div><h2>Capture an observation</h2><p className="muted">Use synthetic data. This record stays on your device.</p><label>Title<input name="title" required maxLength={160} placeholder="A short description"/></label><div className="form-row"><label>Synthetic subject<input name="subject" defaultValue="SYN-001" pattern="SYN-[0-9]{3,6}" required/></label><label>Category<select name="category">{['OBSERVATION','ALLERGY','MEDICATION','VITAL_SIGN','NOTE'].map(c=><option key={c}>{c}</option>)}</select></label></div><label>Observation<textarea name="content" required maxLength={12000} rows={5} placeholder="Record what was observed, with source and context."/></label><label>Privacy<select name="privacy"><option value="SENSITIVE">Sensitive · local only</option><option value="HIGHLY_SENSITIVE">Highly sensitive · hard-pinned local</option></select></label><div className="modal-bottom"><span><LockKeyhole size={14}/>Encrypted on save</span><button className="primary" disabled={busy}>{busy?'Saving…':'Save locally'}<ArrowDownLeft size={16}/></button></div></form></div>}
  </div>;
}
function Stat({label,value,icon,note}:{label:string;value:number;icon:React.ReactNode;note:string}){return <div className="stat"><div><span>{label}</span>{icon}</div><strong>{String(value).padStart(2,'0')}</strong><small>{note}</small></div>}
createRoot(document.getElementById('root')!).render(<App/>);
